# Generated by Django 3.2.13 on 2022-07-06 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urbanRualSet', models.CharField(blank=True, max_length=200, null=True)),
                ('municipalArea', models.CharField(blank=True, max_length=200, null=True)),
                ('urbanDistrict', models.CharField(blank=True, max_length=200, null=True)),
                ('intracityDistrict', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=500, null=True)),
                ('numberHouse', models.CharField(blank=True, max_length=100, null=True)),
                ('numberCorpus', models.CharField(blank=True, max_length=100, null=True)),
                ('numberRootFlat', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventerNumber', models.CharField(blank=True, max_length=300, null=True)),
                ('earlyNumber', models.CharField(blank=True, max_length=300, null=True)),
                ('viewObject', models.CharField(blank=True, choices=[('Здание', 'Здание'), ('Помещение', 'Помещение'), ('Сооружение', 'Сооружение')], max_length=300, null=True)),
                ('nameObject', models.CharField(blank=True, max_length=300, null=True)),
                ('dateInitialInvent', models.CharField(blank=True, max_length=300, null=True)),
                ('dateLastExamination', models.DateField(blank=True, null=True)),
                ('yearCommissioning', models.CharField(blank=True, max_length=300, null=True)),
                ('square', models.CharField(blank=True, max_length=100, null=True)),
                ('residentialSquare', models.CharField(blank=True, max_length=300, null=True)),
                ('ownershipBefore', models.CharField(blank=True, max_length=300, null=True)),
                ('ownershipAfter', models.CharField(blank=True, max_length=600, null=True)),
                ('whoHanded', models.CharField(blank=True, max_length=300, null=True)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('dateIssueInventory', models.DateField(blank=True, null=True)),
                ('returnDate', models.DateField(blank=True, max_length=300, null=True)),
                ('storage', models.CharField(blank=True, max_length=300, null=True, verbose_name='Место хранения документа')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pasportDev.building')),
                ('userbti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file_binary', models.BinaryField(blank=True, editable=True, null=True)),
                ('file_doc', models.ForeignKey(blank=True, db_column='id_pasport', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasportDev.pasportmodel')),
            ],
        ),
    ]
