# Generated by Django 3.2.13 on 2022-07-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasportDev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasportmodel',
            name='dateInputPS',
            field=models.DateField(blank=True, null=True),
        ),
    ]
